name: CI/CD Workflow for Walt.ID Web Wallet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
           node-version: '19'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies 👨🏻‍💻
        run: pnpm i

      - name: Build
        run: pnpm build

      #- name: Run linter 👀
      #  run: yarn lint

      #- name: Run tests 🧪
      #  run: yarn test --passWithNoTests
